server:
  port: 8080
spring:
  application:
    name: accounts-ws
  kafka:
    consumer:
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer